// OTOMATİK ÜRETİLDİ — ELLE DÜZENLEME.
// Kaynak: repo kökündeki el kitabı .md dosyaları.
// Üreten: scripts/rehber-derle.mjs (npm run predev / prebuild)
// Neden gömülü: üretim imajında kökteki .md dosyaları yok (bkz. betiğin başı).

export type RehberSlug =
  | "komisyoncu-rehberi"
  | "bas-komisyoncu-rehberi"
  | "pazarlamaci-el-kitabi"
  | "saha-karti";

export const REHBER_MARKDOWN: Record<RehberSlug, string> = {
  "komisyoncu-rehberi": [
    "# KOMİSYONCU REHBERİ",
    "## Sistemi nasıl kullanacaksın, nasıl para kazanacaksın",
    "",
    "*Bu rehber komisyoncular içindir: sistemin nasıl çalıştığını, kod üretmeyi ve para almayı anlatır. Halıcıya ne anlatacağını, itirazlara ne cevap vereceğini öğrenmek için ayrıca **Pazarlamacı El Kitabı**'nı oku — o satış, bu kullanım rehberidir.*",
    "",
    "---",
    "",
    "# BÖLÜM 1 — İŞİN İŞLEYİŞİ",
    "",
    "## 1.1 İşin özeti",
    "",
    "Sen halı yıkamacı işletmeleri platforma üye yapıyorsun. Getirdiğin her işletme **abone kaldığı sürece, her ay**, aboneliğin **KDV hariç net tutarı** üzerinden anlaşılan yüzdeni alıyorsun.",
    "",
    "**Rakamla:** Abonelik 2.400 TL (KDV dahil), KDV hariç net tutar 2.000 TL. Komisyon oranın %50 ise, o işletme **bir ayın bedelini fiilen ödediğinde** 1.000 TL hak edersin.",
    "",
    "> **Bunu bilerek başla:** komisyon, tahsil edilen ödeme üzerinden işler — sözleşme imzalanınca değil. İşletme ödemeyi bırakırsa o aydan sonrası gelmez. \"12 ay kalırsa 12.000 TL\" bir hesap değil, en iyi ihtimaldir; ortalama kaç ay kalındığını gösterecek kadar uzun süredir çalışmıyoruz. Sana gerçek dışı bir tablo çizip sonra hayal kırıklığı yaşatmak yerine bunu baştan yazıyoruz.",
    "",
    "**Önemli:** Kazancın tek seferlik değil. Getirdiğin müşteri sistemde kaldığı sürece her yenilemede komisyonun işler. Bu yüzden **doğru müşteriye doğru anlatarak** satmak senin de çıkarına: memnun olmayan işletme ilk ay bırakır, senin gelirin de gider.",
    "",
    "## 1.2 Panele giriş",
    "",
    "1. **enyakinhaliyikamaservisi.com/giris** adresine git.",
    "2. Yöneticinin sana verdiği **kullanıcı adı + şifre** ile gir.",
    "3. Giriş yapınca doğrudan **komisyoncu paneline** düşersin. Başka hiçbir sayfaya erişimin yok (halıcı paneli, yönetim vb. sana kapalı) — bu normaldir.",
    "4. **Şifreni değiştirmek istersen:** panelin üstündeki **🔑 Şifremi Değiştir** bağlantısına tıkla (mevcut şifreni bilmen gerekir). Şifreni unuttuysan yöneticiyi ara — sana geçici şifre üretilir.",
    "",
    "**Şifreni unutursan (2026-08-02'den beri):** giriş sayfasındaki **\"Şifremi",
    "unuttum\"** bağlantısına bas, kayıtlı e-postana sıfırlama bağlantısı gelsin",
    "(1 saat geçerli). Bunun çalışması için hesabında **doğrulanmış bir e-posta**",
    "olmalı — panelinin üstündeki **🔑 Şifremi Değiştir** sayfasından ekleyip",
    "6 haneli kodla doğrula. (Yöneticin de senin adına ekleyebilir — ona",
    "adresini söylemen yeterli.) Hiç e-posta yoksa şifreni yalnız yöneticin",
    "sıfırlayabilir.",
    "",
    "**Rehberler panelinde durur:** panelin üstündeki **📚 Rehberler** bağlantısından",
    "bu rehberi ve satış kitapçığını okuyabilir, **HTML olarak indirip** telefonuna",
    "kaydedebilirsin — indirdiğin dosya internet olmadan da açılır.",
    "",
    "## 1.3 Referans kodu — işin kalbi",
    "",
    "**Kodlar TEK KULLANIMLIKTIR.** Sabit, herkese verdiğin bir kodun yoktur. **Her müşteri adayı için panelden ayrı kod üretirsin.**",
    "",
    "**Nasıl:**",
    "- Panelde **\"Referans Kodların\"** bölümündeki **\"+ Kod Üret\"** butonuna bas.",
    "- `HYK-XXXXXX` biçiminde bir kod çıkar (örn. `HYK-K4TN9P`).",
    "- Bu kodu o müşteriye ver. Başka bir müşteriye AYNI kodu veremezsin — bir işletmeye bağlandığı an yanar.",
    "",
    "**Neden böyle:** Hangi kodun hangi müşteriye gittiği kayıtlı olsun, kimse başkasının kodunu kullanamasın diye. Kodun yanlış kişiye geçmesi = senin hakkının başkasına yazılması demekti; bu sistemde mümkün değil.",
    "",
    "**Sınır:** Aynı anda en fazla **25 kullanılmamış kod** tutabilirsin. Bu sınıra takılırsan önce elindekileri kullan. (Kod üretmek bedava, ama 25 boş kod zaten \"dağıtamadığın\" anlamına gelir.)",
    "",
    "**Panelde her kodun durumu görünür:**",
    "- **\"Kullanıma hazır\"** — henüz kimse kullanmadı, verebilirsin.",
    "- **\"Kullanıldı · Hijyen Halı Yıkama\"** — hangi işletmeye bağlandığını gösterir.",
    "",
    "## 1.4 Kod müşteriye nasıl girilir?",
    "",
    "İki yol var:",
    "",
    "**A) İşletme kendi kaydolurken (tercih edilen):**",
    "Halıcı **enyakinhaliyikamaservisi.com/kayit** sayfasından kaydolurken formda **\"Referans kodu\"** alanı vardır. Senin verdiğin kodu oraya yazar. Kayıt tamamlanınca işletme otomatik olarak senin hanene yazılır.",
    "",
    "**B) Yönetici bağlar:**",
    "Halıcı kodu girmeyi unuttuysa yönetici, işletme sayfasından kodu girerek bağlayabilir. Bu durumda yöneticiye kodu ve işletme adını bildirmen gerekir.",
    "",
    "> ⚠️ **EN KRİTİK NOKTA:** Kod girilmeden kayıt tamamlanırsa o işletme **senin hanene yazılmaz** ve emeğin boşa gider. En sağlamı, kaydı işletmeyle **birlikte** yapmak (yanında ya da telefonda adım adım) ve kodun girildiğini gözünle görmek. Yanında olamıyorsan kodu yaz-ver, sonra \"girdin mi?\" diye teyit et.",
    "",
    "## 1.5 Kazancını takip etme",
    "",
    "Panelinde üç kutu görürsün:",
    "- **Getirdiğin işletme** — kaç işletme bağlandı",
    "- **Toplam komisyon** — bugüne kadar hak ettiğin toplam",
    "- **Ödenen** — sana fiilen ödenmiş kısım",
    "",
    "Altta **\"Getirdiğin İşletmeler\"** listesi vardır; her birinin aboneliği aktif mi pasif mi görürsün. Abonelik pasifse o aydan komisyon işlemez — işletme yeniden öderse devam eder.",
    "",
    "En altta **\"Komisyon Kayıtları\"** tablosu: hangi tarihte, hangi işletmeden, ne kadar, ödendi mi.",
    "",
    "**Komisyon ne zaman işler?** İşletme abonelik ödemesini yaptığı anda otomatik. Sen bir şey yapmazsın, yönetici de elle girmez — sistem hesaplar.",
    "",
    "## 1.6 Paranı alma — HER AYIN SON GÜNÜ OTOMATİK",
    "",
    "**Talep açmana gerek yok:** ayın son günü, bakiyesi olan her AKTİF komisyoncuya ödeme talebi",
    "**kendiliğinden** oluşur; yönetim havaleleri toplu yapar, panelinde \"Ödendi\"",
    "görürsün. Ay içinde biriken her tahakkuk o ayın sonunda ödenir.",
    "",
    "**Tek şartı:** panelin **\"Ödemem\"** bölümünde **IBAN + hesap sahibi ad soyad**",
    "kayıtlı olmalı. Eksikse o ay ödeme BEKLETİLİR (panelde uyarı zili çalar);",
    "ekleyince bir sonraki ay sonunda düzenli akışa girersin.",
    "",
    "**Kurallar:**",
    "- Havaleyi yönetici yapar (sistem otomatik para göndermez); stopaj gerekiyorsa",
    "  sistem ödemede otomatik hesaplar (bkz. 1.6b).",
    "- Talep sonuçlanınca panelde durumu görürsün: Bekliyor / Ödendi / Reddedildi.",
    "",
    "## 1.6b Vergi ve ödeme belgeleri (2026-07-31 eklendi)",
    "",
    "**IBAN kaydederken artık hesap sahibinin ADI SOYADI da zorunlu** — bankalar",
    "isim uyuşmazlığında havaleyi geri çeviriyor. Banka kaydındaki halinle yaz.",
    "",
    "**Vergi tarafında iki durum var, hangisindeysen ona göre ödeme alırsın:**",
    "",
    "**A) Vergi mükellefiysen (şahıs şirketi/şirket — fatura kesebiliyorsan):**",
    "Ödeme talebin onaylanınca platforma **fatura kesersin**, brüt tutarın tamamı",
    "sana havale edilir. Vergini kendi tarafında beyan edersin.",
    "",
    "**B) Vergi mükellefi değilsen (fatura kesemiyorsan):**",
    "Aylık kazancın **10.000 TL'ye ulaştığı aylarda (10.000 dahil)** platform yasal olarak",
    "**%15 stopaj** keserek öder — kesinti sistemce ödeme anında OTOMATİK",
    "hesaplanır, elle oynanmaz. Belgesi **gider pusulası**dır, ödemede platform",
    "düzenler, bir nüshasını imzalayıp iade edersin. Örnek: 12.000 TL brüt talebin",
    "→ 1.800 TL stopaj kesilir → **10.200 TL net** hesabına yatar (kesilen vergi",
    "senin adına devlete beyan edilir — kaybolmaz, senin ödenmiş vergindir).",
    "Bunun için panelde **T.C. kimlik numaranı ve adresini** ödeme bilgilerine",
    "eklemen gerekir (vergi belgesinin zorunlu alanları). Ödeme banka havalesiyle",
    "yapıldığı için **dekont, kanunen gider pusulası yerine geçer** (VUK 234) —",
    "sana ayrıca imzalatılacak döküm, dekontun stopaj ayrıntısını gösteren ekidir.",
    "",
    "⚠️ Oran ve eşik uygulaması mali müşavir teyidine tabidir; tereddüdün varsa",
    "yöneticine sor.",
    "",
    "## 1.7 İndirim yetkisi (varsa)",
    "",
    "Bazı komisyoncularda **indirim yetkisi** vardır. Sende varsa, kod üretirken iki alan daha görürsün: **indirim yüzdesi** ve **süre (ay)**.",
    "",
    "Örnek: %10 / 3 ay yazıp kod üretirsen, o kodla kaydolan işletme **3 ay boyunca aboneliği %10 indirimli** öder.",
    "",
    "**Standart tavan: en fazla %20 indirim, en fazla 12 ay.** Yönetici sana özel farklı bir tavan tanımlayabilir (daha yüksek ya da daha düşük); **senin tavanın panelindeki kod üretme bölümünde yazar** ve sistem üstünü kabul etmez. Panelde ne yazıyorsa söz verebileceğin en yüksek indirim odur.",
    "",
    "**Bilmen gerekenler:**",
    "- Bu yetkiyi sadece yönetici verir. Panelinde bu alanlar yoksa yetkin yok demektir — **müşteriye indirim sözü verme.**",
    "- İndirim, senin komisyonunu da düşürür: komisyon her zaman **fiilen tahsil edilen** tutar üzerinden hesaplanır. %20 indirimli abonelikte komisyonun da %20 düşer. İndirimi \"satışı kapatmak için\" kullan, alışkanlık haline getirme.",
    "- Alanları boş bırakırsan kod indirimsiz olur.",
    "",
    "## 1.8 Hesabın pasife alınırsa",
    "",
    "Yönetici hesabını pasife alabilir. Pasifken:",
    "- Kod üretemezsin,",
    "- Ay sonu ödeme turu seni atlar (bakiyen durur, silinmez — aktifleşince ödenir),",
    "- **O dönemde yapılan ödemelerden komisyon işlemez** ve hesabın tekrar açılsa bile o dönem geri gelmez.",
    "",
    "Bu yüzden pasife alınma durumunda hemen yöneticiyle konuş.",
    "",
    "---",
    "",
    "# BÖLÜM 2 — SIK SORULANLAR",
    "",
    "**Kodu verdim ama müşteri kaydolmadı, kod yandı mı?**",
    "Hayır. Kod ancak bir işletmeye **bağlandığında** yanar. Kaydolmadıysa kod hâlâ kullanıma hazırdır.",
    "",
    "**Müşteri kodu girmeyi unuttu, ne olur?**",
    "İşletme senin hanene yazılmaz. Fark ettiğin an yöneticiye ulaş — henüz kullanılmamış bir kodunla bağlanabilir. Ne kadar geç kalırsan o kadar zorlaşır.",
    "",
    "**Komisyonum ne zaman işler?**",
    "İşletme abonelik ödemesini yaptığı anda otomatik. İlk ödeme + her yenileme.",
    "",
    "**İşletme aboneliğini yenilemezse?**",
    "O ay komisyon işlemez. Tekrar öderse kaldığı yerden devam eder — yeniden kod vermeye gerek yok.",
    "",
    "**İşletme indirimli abone olduysa?**",
    "Komisyon fiilen tahsil edilen tutardan hesaplanır; indirim oranında senin payın da düşer.",
    "",
    "**Paramı ne zaman alırım?**",
    "Her ayın son günü — bakiyen otomatik talebe dönüşür, yönetim havale eder (bkz. 1.6). IBAN + ad soyad kayıtlı değilse o ay bekletilir.",
    "",
    "**Panelde göremediğim bir işletme var, getiren benim.**",
    "Muhtemelen kod girilmemiş ya da başka bir kodla kaydolmuş. Yöneticiye işletme adı + verdiğin kodla başvur.",
    "",
    "---",
    "",
    "",
    "## 1.9 Demo panel — tek tıkla göster",
    "",
    "Dükkânda anlatmak yerine **göster**. Panelindeki *Demo Panelim* kutusunda iki",
    "düğme var, ikisi de **şifre sormaz**:",
    "",
    "- **🏪 Demo halıcı paneli** — sipariş listesi, kasa, fotoğraflar, fiyat onayı",
    "- **🚚 Demo şoför ekranı** — işin şoföre nasıl düştüğü, fotoğraf çekme, teslim",
    "",
    "Halıcıya önce paneli, sonra şoför ekranını göster: \"işi böyle görüyorsun,",
    "şoförün de bunu görüyor\". Demo ekranlarının üstünde mor bir şerit ve",
    "**\"Komisyoncu paneline dön\"** düğmesi vardır — bir tıkla kendi paneline",
    "dönersin.",
    "",
    "**Panelde mutlaka gösterilecek üç ekran (sırayla):**",
    "1. **Siparişler** — \"işin buraya düşüyor, tek tık ilerletiyorsun\"",
    "2. **Halı Bul** — dükkândaki halıların fotoğraf duvarı; her karede halı",
    "   numarası, altında müşterinin adı. *\"Elinde halı var, kimin olduğunu",
    "   bilmiyorsun: buradan fotoğrafından buluyorsun.\"* Yoğun dükkânda en çok",
    "   ilgi çeken ekran budur.",
    "3. **Kasa** — \"ay sonunda kâr mı ettin zarar mı, tek ekranda\"",
    "",
    "> Demo hesabındaki hiçbir şey gerçek değildir: siparişler örnektir, telefon",
    "> numaraları sahtedir, kimseye mesaj gitmez. Demo, müşteri aramalarında ve",
    "> platform sayaçlarında görünmez.",
    "",
    "## 1.10 Ücretsiz deneme yetkisi (varsa)",
    "",
    "Yöneticin sana **ücretsiz deneme** yetkisi verdiyse, kod üretirken",
    "**\"Ücretsiz deneme\"** açılır listesinden **15 gün** ya da **1 ay**",
    "seçebilirsin. O kodla kaydolan işletme, seçtiğin süre boyunca **hiç ödeme",
    "yapmadan** yayına girer; süre bitince normal aidat başlar.",
    "",
    "**Bilmen gerekenler:**",
    "- Deneme süresince **komisyon işlemez.** Kazancın, işletme **ilk parayı",
    "  ödediğinde** başlar. Yani bedava dağıtmak sana kazanç getirmez —",
    "  deneme, kararsız halıcıyı ikna etmek için bir **satış aracıdır**.",
    "- Panelinde bu alan yoksa yetkin yok demektir; **müşteriye deneme sözü verme.**",
    "- Deneme ile indirim aynı kodda birleşebilir: önce ücretsiz dönem işler,",
    "  bitince indirimli fiyattan devam eder.",
    "- Kaç günlük verebileceğini yönetici belirler; listede yalnız yetkin kadarı çıkar.",
    "",
    "**Saha cümlesi:** *\"Bir ay bedava dene abi. Beğenmezsen bırakırsın, tek kuruş",
    "ödemezsin. Beğenirsen zaten devam edersin.\"*",
    "",
    "## SON SÖZ",
    "",
    "Bu sistem sana üç şey veriyor: **kendi panelin** (kazancın şeffaf, kimse \"sen ne kadar getirdin\" diye tartışmaz), **tek kullanımlık kodlar** (hakkın karışmaz), **her ay tekrarlayan gelir** (bir kez satarsın, aylarca kazanırsın).",
    "",
    "Karşılığında senden beklenen tek şey: **doğru anlatarak sat.** Yalan vaatle giren işletme ilk ay bırakır; senin gelirin de onunla gider. Memnun işletme senin düzenli maaşındır.",
  ].join("\n"),
  "bas-komisyoncu-rehberi": [
    "# BAŞ KOMİSYONCU REHBERİ",
    "## Kendi ekibini kur, havuz payını yönet",
    "",
    "*Bu rehber BAŞ KOMİSYONCULAR içindir — havuz payı ve ekip yönetimi dahil.*",
    "",
    "> ⚠️ **Bu rehberi alt komisyoncularınla PAYLAŞMA.** Onlara panelindeki **Komisyoncu Rehberi**'ni ver; o sürümde havuz matematiği yoktur. (Zaten alt komisyoncunun panelinde bu rehber görünmez — sistem süzer.)",
    "",
    "*Sistemin nasıl çalıştığını anlatır. Halıcıya ne anlatacağını, itirazlara ne cevap vereceğini öğrenmek için ayrıca **Pazarlamacı El Kitabı**'nı oku — o satış, bu kullanım rehberidir.*",
    "",
    "---",
    "",
    "# BÖLÜM 1 — TEMEL İŞLEYİŞ (senin için de geçerli)",
    "",
    "## 1.1 İşin özeti",
    "",
    "Sen halı yıkamacı işletmeleri platforma üye yapıyorsun. Getirdiğin her işletme **abone kaldığı sürece, her ay**, aboneliğin **KDV hariç net tutarı** üzerinden anlaşılan yüzdeni alıyorsun.",
    "",
    "**Rakamla:** Abonelik 2.400 TL (KDV dahil), KDV hariç net tutar 2.000 TL. Komisyon oranın %50 ise, o işletme **bir ayın bedelini fiilen ödediğinde** 1.000 TL hak edersin.",
    "",
    "> **Bunu bilerek başla:** komisyon, tahsil edilen ödeme üzerinden işler — sözleşme imzalanınca değil. İşletme ödemeyi bırakırsa o aydan sonrası gelmez. \"12 ay kalırsa 12.000 TL\" bir hesap değil, en iyi ihtimaldir; ortalama kaç ay kalındığını gösterecek kadar uzun süredir çalışmıyoruz. Kendi ekibine de bu cümleyi aynen kur — şişirilmiş beklentiyle gelen komisyoncu ilk ayda bırakır.",
    "",
    "**Önemli:** Kazancın tek seferlik değil. Getirdiğin müşteri sistemde kaldığı sürece her yenilemede komisyonun işler. Bu yüzden **doğru müşteriye doğru anlatarak** satmak senin de çıkarına: memnun olmayan işletme ilk ay bırakır, senin gelirin de gider.",
    "",
    "## 1.2 Panele giriş",
    "",
    "1. **enyakinhaliyikamaservisi.com/giris** adresine git.",
    "2. Yöneticinin sana verdiği **kullanıcı adı + şifre** ile gir.",
    "3. Giriş yapınca doğrudan **komisyoncu paneline** düşersin. Başka hiçbir sayfaya erişimin yok (halıcı paneli, yönetim vb. sana kapalı) — bu normaldir.",
    "4. **Şifreni değiştirmek istersen:** panelin üstündeki **🔑 Şifremi Değiştir** bağlantısına tıkla (mevcut şifreni bilmen gerekir). Şifreni unuttuysan yöneticiyi ara — sana geçici şifre üretilir.",
    "",
    "**Şifreni unutursan (2026-08-02'den beri):** giriş sayfasındaki **\"Şifremi",
    "unuttum\"** bağlantısına bas, kayıtlı e-postana sıfırlama bağlantısı gelsin",
    "(1 saat geçerli). Bunun çalışması için hesabında **doğrulanmış bir e-posta**",
    "olmalı — panelinin üstündeki **🔑 Şifremi Değiştir** sayfasından ekleyip",
    "6 haneli kodla doğrula. (Yöneticin de senin adına ekleyebilir — ona",
    "adresini söylemen yeterli.) Hiç e-posta yoksa şifreni yalnız yöneticin",
    "sıfırlayabilir.",
    "",
    "**Rehberler panelinde durur:** panelin üstündeki **📚 Rehberler** bağlantısından",
    "bu rehberi, satış kitapçığını ve **ekibine vereceğin Komisyoncu Rehberi'ni**",
    "okuyabilir, **HTML olarak indirip** telefonuna kaydedebilirsin — indirdiğin",
    "dosya internet olmadan da açılır.",
    "",
    "## 1.3 Referans kodu — işin kalbi",
    "",
    "**Kodlar TEK KULLANIMLIKTIR.** Sabit, herkese verdiğin bir kodun yoktur. **Her müşteri adayı için panelden ayrı kod üretirsin.**",
    "",
    "**Nasıl:**",
    "- Panelde **\"Referans Kodların\"** bölümündeki **\"+ Kod Üret\"** butonuna bas.",
    "- `HYK-XXXXXX` biçiminde bir kod çıkar (örn. `HYK-K4TN9P`).",
    "- Bu kodu o müşteriye ver. Başka bir müşteriye AYNI kodu veremezsin — bir işletmeye bağlandığı an yanar.",
    "",
    "**Neden böyle:** Hangi kodun hangi müşteriye gittiği kayıtlı olsun, kimse başkasının kodunu kullanamasın diye. Kodun yanlış kişiye geçmesi = senin hakkının başkasına yazılması demekti; bu sistemde mümkün değil.",
    "",
    "**Sınır:** Aynı anda en fazla **25 kullanılmamış kod** tutabilirsin. Bu sınıra takılırsan önce elindekileri kullan. (Kod üretmek bedava, ama 25 boş kod zaten \"dağıtamadığın\" anlamına gelir.)",
    "",
    "**Panelde her kodun durumu görünür:**",
    "- **\"Kullanıma hazır\"** — henüz kimse kullanmadı, verebilirsin.",
    "- **\"Kullanıldı · Hijyen Halı Yıkama\"** — hangi işletmeye bağlandığını gösterir.",
    "",
    "## 1.4 Kod müşteriye nasıl girilir?",
    "",
    "İki yol var:",
    "",
    "**A) İşletme kendi kaydolurken (tercih edilen):**",
    "Halıcı **enyakinhaliyikamaservisi.com/kayit** sayfasından kaydolurken formda **\"Referans kodu\"** alanı vardır. Senin verdiğin kodu oraya yazar. Kayıt tamamlanınca işletme otomatik olarak senin hanene yazılır.",
    "",
    "**B) Yönetici bağlar:**",
    "Halıcı kodu girmeyi unuttuysa yönetici, işletme sayfasından kodu girerek bağlayabilir. Bu durumda yöneticiye kodu ve işletme adını bildirmen gerekir.",
    "",
    "> ⚠️ **EN KRİTİK NOKTA:** Kod girilmeden kayıt tamamlanırsa o işletme **senin hanene yazılmaz** ve emeğin boşa gider. En sağlamı, kaydı işletmeyle **birlikte** yapmak (yanında ya da telefonda adım adım) ve kodun girildiğini gözünle görmek. Yanında olamıyorsan kodu yaz-ver, sonra \"girdin mi?\" diye teyit et.",
    "",
    "## 1.5 Kazancını takip etme",
    "",
    "Panelinde üç kutu görürsün:",
    "- **Getirdiğin işletme** — kaç işletme bağlandı",
    "- **Toplam komisyon** — bugüne kadar hak ettiğin toplam",
    "- **Ödenen** — sana fiilen ödenmiş kısım",
    "",
    "Altta **\"Getirdiğin İşletmeler\"** listesi vardır; her birinin aboneliği aktif mi pasif mi görürsün. Abonelik pasifse o aydan komisyon işlemez — işletme yeniden öderse devam eder.",
    "",
    "En altta **\"Komisyon Kayıtları\"** tablosu: hangi tarihte, hangi işletmeden, ne kadar, ödendi mi.",
    "",
    "**Komisyon ne zaman işler?** İşletme abonelik ödemesini yaptığı anda otomatik. Sen bir şey yapmazsın, yönetici de elle girmez — sistem hesaplar.",
    "",
    "## 1.6 Paranı alma — HER AYIN SON GÜNÜ OTOMATİK",
    "",
    "**Talep açmana gerek yok:** ayın son günü, bakiyesi olan her AKTİF komisyoncuya ödeme talebi",
    "**kendiliğinden** oluşur; yönetim havaleleri toplu yapar, panelinde \"Ödendi\"",
    "görürsün. Ay içinde biriken her tahakkuk o ayın sonunda ödenir.",
    "",
    "**Tek şartı:** panelin **\"Ödemem\"** bölümünde **IBAN + hesap sahibi ad soyad**",
    "kayıtlı olmalı. Eksikse o ay ödeme BEKLETİLİR (panelde uyarı zili çalar);",
    "ekleyince bir sonraki ay sonunda düzenli akışa girersin.",
    "",
    "**Kurallar:**",
    "- Havaleyi yönetici yapar (sistem otomatik para göndermez); stopaj gerekiyorsa",
    "  sistem ödemede otomatik hesaplar (bkz. 1.6b).",
    "- Talep sonuçlanınca panelde durumu görürsün: Bekliyor / Ödendi / Reddedildi.",
    "",
    "## 1.6b Vergi ve ödeme belgeleri (2026-07-31 eklendi)",
    "",
    "**IBAN kaydederken artık hesap sahibinin ADI SOYADI da zorunlu** — bankalar",
    "isim uyuşmazlığında havaleyi geri çeviriyor. Banka kaydındaki halinle yaz.",
    "",
    "**Vergi tarafında iki durum var, hangisindeysen ona göre ödeme alırsın:**",
    "",
    "**A) Vergi mükellefiysen (şahıs şirketi/şirket — fatura kesebiliyorsan):**",
    "Ödeme talebin onaylanınca platforma **fatura kesersin**, brüt tutarın tamamı",
    "sana havale edilir. Vergini kendi tarafında beyan edersin.",
    "",
    "**B) Vergi mükellefi değilsen (fatura kesemiyorsan):**",
    "Aylık kazancın **10.000 TL'ye ulaştığı aylarda (10.000 dahil)** platform yasal olarak",
    "**%15 stopaj** keserek öder — kesinti sistemce ödeme anında OTOMATİK",
    "hesaplanır, elle oynanmaz. Belgesi **gider pusulası**dır, ödemede platform",
    "düzenler, bir nüshasını imzalayıp iade edersin. Örnek: 12.000 TL brüt talebin",
    "→ 1.800 TL stopaj kesilir → **10.200 TL net** hesabına yatar (kesilen vergi",
    "senin adına devlete beyan edilir — kaybolmaz, senin ödenmiş vergindir).",
    "Bunun için panelde **T.C. kimlik numaranı ve adresini** ödeme bilgilerine",
    "eklemen gerekir (vergi belgesinin zorunlu alanları). Ödeme banka havalesiyle",
    "yapıldığı için **dekont, kanunen gider pusulası yerine geçer** (VUK 234) —",
    "sana ayrıca imzalatılacak döküm, dekontun stopaj ayrıntısını gösteren ekidir.",
    "",
    "⚠️ Oran ve eşik uygulaması mali müşavir teyidine tabidir; tereddüdün varsa",
    "yöneticine sor.",
    "",
    "## 1.7 İndirim yetkisi (varsa)",
    "",
    "Bazı komisyoncularda **indirim yetkisi** vardır. Sende varsa, kod üretirken iki alan daha görürsün: **indirim yüzdesi** ve **süre (ay)**.",
    "",
    "Örnek: %10 / 3 ay yazıp kod üretirsen, o kodla kaydolan işletme **3 ay boyunca aboneliği %10 indirimli** öder.",
    "",
    "**Standart tavan: en fazla %20 indirim, en fazla 12 ay.** Yönetici sana özel farklı bir tavan tanımlayabilir (daha yüksek ya da daha düşük); **senin tavanın panelindeki kod üretme bölümünde yazar** ve sistem üstünü kabul etmez. Panelde ne yazıyorsa söz verebileceğin en yüksek indirim odur.",
    "",
    "**Bilmen gerekenler:**",
    "- Bu yetkiyi sadece yönetici verir. Panelinde bu alanlar yoksa yetkin yok demektir — **müşteriye indirim sözü verme.**",
    "- İndirim, senin komisyonunu da düşürür: komisyon her zaman **fiilen tahsil edilen** tutar üzerinden hesaplanır. %20 indirimli abonelikte komisyonun da %20 düşer. İndirimi \"satışı kapatmak için\" kullan, alışkanlık haline getirme.",
    "- Alanları boş bırakırsan kod indirimsiz olur.",
    "",
    "## 1.8 Hesabın pasife alınırsa",
    "",
    "Yönetici hesabını pasife alabilir. Pasifken:",
    "- Kod üretemezsin,",
    "- Ay sonu ödeme turu seni atlar (bakiyen durur, silinmez — aktifleşince ödenir),",
    "- **O dönemde yapılan ödemelerden komisyon işlemez** ve hesabın tekrar açılsa bile o dönem geri gelmez.",
    "",
    "Bu yüzden pasife alınma durumunda hemen yöneticiyle konuş.",
    "",
    "---",
    "",
    "# BÖLÜM 2 — BAŞ KOMİSYONCU",
    "",
    "Baş komisyoncuysan yukarıdaki her şey senin için de geçerli — **ek olarak kendi ekibini kurarsın.**",
    "",
    "",
    "## 1.9 Demo panel — tek tıkla göster",
    "",
    "Dükkânda anlatmak yerine **göster**. Panelindeki *Demo Panelim* kutusunda iki",
    "düğme var, ikisi de **şifre sormaz**:",
    "",
    "- **🏪 Demo halıcı paneli** — sipariş listesi, kasa, fotoğraflar, fiyat onayı",
    "- **🚚 Demo şoför ekranı** — işin şoföre nasıl düştüğü, fotoğraf çekme, teslim",
    "",
    "Halıcıya önce paneli, sonra şoför ekranını göster: \"işi böyle görüyorsun,",
    "şoförün de bunu görüyor\". Demo ekranlarının üstünde mor bir şerit ve",
    "**\"Komisyoncu paneline dön\"** düğmesi vardır — bir tıkla kendi paneline",
    "dönersin.",
    "",
    "**Panelde mutlaka gösterilecek üç ekran (sırayla):**",
    "1. **Siparişler** — \"işin buraya düşüyor, tek tık ilerletiyorsun\"",
    "2. **Halı Bul** — dükkândaki halıların fotoğraf duvarı; her karede halı",
    "   numarası, altında müşterinin adı. *\"Elinde halı var, kimin olduğunu",
    "   bilmiyorsun: buradan fotoğrafından buluyorsun.\"* Yoğun dükkânda en çok",
    "   ilgi çeken ekran budur. Ekibine de bunu öğret.",
    "3. **Kasa** — \"ay sonunda kâr mı ettin zarar mı, tek ekranda\"",
    "",
    "> Demo hesabındaki hiçbir şey gerçek değildir: siparişler örnektir, telefon",
    "> numaraları sahtedir, kimseye mesaj gitmez. Demo, müşteri aramalarında ve",
    "> platform sayaçlarında görünmez.",
    "",
    "## 1.10 Ücretsiz deneme yetkisi (varsa)",
    "",
    "Yöneticin sana **ücretsiz deneme** yetkisi verdiyse, kod üretirken",
    "**\"Ücretsiz deneme\"** açılır listesinden **15 gün** ya da **1 ay**",
    "seçebilirsin. O kodla kaydolan işletme, seçtiğin süre boyunca **hiç ödeme",
    "yapmadan** yayına girer; süre bitince normal aidat başlar.",
    "",
    "**Bilmen gerekenler:**",
    "- Deneme süresince **komisyon işlemez.** Kazancın, işletme **ilk parayı",
    "  ödediğinde** başlar. Yani bedava dağıtmak sana kazanç getirmez —",
    "  deneme, kararsız halıcıyı ikna etmek için bir **satış aracıdır**.",
    "- Panelinde bu alan yoksa yetkin yok demektir; **müşteriye deneme sözü verme.**",
    "- Deneme ile indirim aynı kodda birleşebilir: önce ücretsiz dönem işler,",
    "  bitince indirimli fiyattan devam eder.",
    "- Kaç günlük verebileceğini yönetici belirler; listede yalnız yetkin kadarı çıkar.",
    "",
    "**Saha cümlesi:** *\"Bir ay bedava dene abi. Beğenmezsen bırakırsın, tek kuruş",
    "ödemezsin. Beğenirsen zaten devam edersin.\"*",
    "",
    "## 2.1 Havuz payı mantığı",
    "",
    "Sana bir **havuz payı** tanımlanır (genelde **%50**). Bu, o ağaçtan platformun ödeyeceği toplam komisyondur ve **bölüşümünü sen belirlersin.**",
    "",
    "**Kendi getirdiğin müşteri:** Havuzun tamamı senindir. %50 havuzda, kendi kodunla getirdiğin işletmeden **ayda 1.000 TL** alırsın.",
    "",
    "**Komisyoncunun getirdiği müşteri:** Ona verdiğin yüzde ondan, **kalan fark senden**:",
    "",
    "| Alt komisyoncuya verdiğin | O alır | Sen alırsın |",
    "|---|---|---|",
    "| %25 | 500 TL | **500 TL** |",
    "| %30 | 600 TL | **400 TL** |",
    "| %40 | 800 TL | **200 TL** |",
    "| %50 (havuzun tamamı) | 1.000 TL | **0 TL** |",
    "| %0 | 0 TL | **1.000 TL** |",
    "",
    "Yani komisyoncuya ne kadar cömert davranırsan senin payın o kadar azalır — ama iyi çalışan komisyoncu daha çok müşteri getirir. Dengeyi sen kurarsın.",
    "",
    "**Platform hiçbir durumda havuzdan fazla ödemez.** Alt komisyoncuya havuzun üstünde yüzde veremezsin, sistem engeller.",
    "",
    "## 2.2 Komisyoncu hesabı açma",
    "",
    "Panelinde **\"Komisyoncularım\"** bölümü vardır.",
    "",
    "1. **\"+ Yeni Komisyoncu Aç\"** formunu doldur: ad soyad, telefon, kullanıcı adı, şifre, **komisyon yüzdesi** (0 ile havuz payın arası).",
    "2. **\"Komisyoncu Oluştur\"**a bas.",
    "3. Ekranda çıkan kullanıcı adı ve şifreyi kişiye ilet. O da **/giris**'ten girip kendi panelinden müşteri başına kod üretmeye başlar.",
    "",
    "**Sınır yok** — istediğin kadar komisyoncu açabilirsin.",
    "",
    "**İndirim yetkisi verme (sende varsa):** Hesap açarken **\"İndirim yetkisi ver\"** kutucuğunu işaretlersen, o komisyoncu da kod üretirken abonelik fiyatına indirim tanımlayabilir. Sonradan da ekip listesindeki **\"İndirim yetkisi ver / İndirimi kaldır\"** butonuyla açıp kapatabilirsin.",
    "",
    "> ⚠️ **Sende indirim yetkisi yoksa altına da veremezsin** — sistem engeller.",
    "",
    "**Ücretsiz deneme yetkisi verme (sende varsa):** Hesap açarken **\"Ücretsiz",
    "deneme yetkisi ver\"** kutusunu işaretlersen, o komisyoncu da kodlarına deneme",
    "koyabilir. Kaç günlük verebileceğini sen seçersin — **kendi tavanını aşamaz**.",
    "Aynı kural indirimde de geçerli: sana %10 tavan verildiyse altına en fazla %10",
    "verebilirsin.",
    ">",
    "> **Parasal etkisi:** İndirim, tahsil edilen tutarı düşürür; komisyon her zaman **fiilen tahsil edilen** tutardan hesaplandığı için hem platformun hem **senin** payın düşer. Örnek: %20 indirimli abonelikte havuzun da %20 küçülür. İndirimi satışı kapatmak için kullan, standart hale getirme.",
    ">",
    "> İndirim yetkisini geri alman, o komisyoncunun **daha önce verdiği** indirimleri iptal etmez (verilmiş söz tutulur) — yalnız yeni indirimli kod üretemez.",
    "",
    "**Açtığın hesabın yapamayacağı tek şey:**",
    "- Kendi altına komisyoncu **açamaz** (sistem iki kademelidir).",
    "",
    "## 2.3 Ekibini yönetme",
    "",
    "Listede her komisyoncunun yanında şunlar yazar: **verdiğin yüzde**, **sana kalan fark**, **kaç işletme getirdiği**, aktif/pasif durumu.",
    "",
    "**\"Pasife al\" butonu** — dikkatli kullan:",
    "",
    "> Bir komisyoncuyu pasife alırsan **yalnız komisyon durur.** Onun getirdiği işletmelerin aboneliği, yayını, siparişleri hiç etkilenmez — ödemeye devam ederler.",
    ">",
    "> Ama pasif geçen dönemde **ne ona ne sana** pay yazılır ve sonradan aktive etsen bile **o dönem geri gelmez.** Yeni ödemelerden itibaren işler.",
    "",
    "Yani pasife alma \"bu kişiyle çalışmayı durdurdum\" demektir; geçici bir duraklatma aracı değildir.",
    "",
    "**Not:** Yönetici bir komisyoncuyu dondurduysa sen onu geri açamazsın (panelde \"yönetim dondurdu\" yazar). Bu bilinçli bir kuraldır.",
    "",
    "## 2.4 Kazancını takip etme",
    "",
    "Panelinde üstteki toplam kutusu **kendi + ekip** kazancını birleştirir. \"Komisyoncularım\" bölümünde ise ayrıca:",
    "- **\"Ekipten kazancın\"** — havuz farkından gelen toplam ve ne kadarının ödendiği,",
    "- **\"Ekipten Kazançların\"** tablosu — hangi işletme, hangi komisyoncu, senin payın ne kadar, ödendi mi.",
    "",
    "**Ödeme alma yöntemin komisyoncularla aynıdır** (bkz. 1.6): her ayın son günü otomatik — talep, kendi payın **ve** ekipten gelen havuz farkını birlikte kapsar.",
    "",
    "---",
    "",
    "# BÖLÜM 3 — SIK SORULANLAR",
    "",
    "**Kodu verdim ama müşteri kaydolmadı, kod yandı mı?**",
    "Hayır. Kod ancak bir işletmeye **bağlandığında** yanar. Kaydolmadıysa kod hâlâ kullanıma hazırdır.",
    "",
    "**Müşteri kodu girmeyi unuttu, ne olur?**",
    "İşletme senin hanene yazılmaz. Fark ettiğin an yöneticiye ulaş — henüz kullanılmamış bir kodunla bağlanabilir. Ne kadar geç kalırsan o kadar zorlaşır.",
    "",
    "**Komisyonum ne zaman işler?**",
    "İşletme abonelik ödemesini yaptığı anda otomatik. İlk ödeme + her yenileme.",
    "",
    "**İşletme aboneliğini yenilemezse?**",
    "O ay komisyon işlemez. Tekrar öderse kaldığı yerden devam eder — yeniden kod vermeye gerek yok.",
    "",
    "**İşletme indirimli abone olduysa?**",
    "Komisyon fiilen tahsil edilen tutardan hesaplanır; indirim oranında senin payın da düşer.",
    "",
    "**Paramı ne zaman alırım?**",
    "Her ayın son günü — bakiyen otomatik talebe dönüşür, yönetim havale eder (bkz. 1.6). IBAN + ad soyad kayıtlı değilse o ay bekletilir.",
    "",
    "**Panelde göremediğim bir işletme var, getiren benim.**",
    "Muhtemelen kod girilmemiş ya da başka bir kodla kaydolmuş. Yöneticiye işletme adı + verdiğin kodla başvur.",
    "",
    "---",
    "",
    "## SON SÖZ",
    "",
    "Bu sistem sana üç şey veriyor: **kendi panelin** (kazancın şeffaf, kimse \"sen ne kadar getirdin\" diye tartışmaz), **tek kullanımlık kodlar** (hakkın karışmaz), **her ay tekrarlayan gelir** (bir kez satarsın, aylarca kazanırsın).",
    "",
    "Karşılığında senden beklenen tek şey: **doğru anlatarak sat.** Yalan vaatle giren işletme ilk ay bırakır; senin gelirin de onunla gider. Memnun işletme senin düzenli maaşındır.",
  ].join("\n"),
  "pazarlamaci-el-kitabi": [
    "# PAZARLAMACI EL KİTABI",
    "## enyakinhaliyikamaservisi.com — Komisyoncu Tanıtım ve Satış Rehberi",
    "",
    "*Bu kitapçık senin için hazırlandı. Önce baştan sona bir kere oku ki platformu tam tanı; sonra dükkân ziyaretinde veya telefonda bölüm bölüm kullan. Ezberlemene gerek yok — hikâyeleri kendi cümlelerinle anlat, ama rakamları aynen ver. Esnafa teknik laf değil, kazancını anlatacaksın.*",
    "",
    "---",
    "",
    "## 1. PLATFORM NEDİR? (Önce sen anla)",
    "",
    "Satmadan önce ne sattığını bilmen lazım. enyakinhaliyikamaservisi.com, Türkiye'nin her yerindeki halı yıkamacıları, internette halı yıkamacı arayan müşterilerle buluşturan bir pazar yeridir. Site şu an canlıdır ve çalışmaktadır. Müşteri siteye girer, adresini veya konumunu verir, kendisine en yakın halı yıkamacıları listelenir; beğendiği işletmeden tek tıkla online sipariş verir ya da WhatsApp'tan, telefondan direkt ulaşır. İşletme bu sisteme aylık sabit abonelikle katılır: **2.000 TL + KDV = 2.400 TL/ay.** Sipariş başına komisyon yok, müşteri başına pay yok, ciro kesintisi yok, yıllık taahhüt yok. Bu cümleyi ezberle, çünkü elindeki en güçlü koz bu.",
    "",
    "Ama dikkat: bu sadece \"müşteri getiren site\" değil. Asıl değeri, işletmeye verilen **komple iş yönetim sistemi:** sipariş paneli, müşteriye giden otomatik bildirimler (WhatsApp + e-posta — 31.07.2026'dan beri WhatsApp CANLI ve mesajlarda tıklanabilir takip/onay BUTONU var), onaylı fiyat bildirimi, fotoğraflı alım-teslim kaydı, şoför takibi, raporlar... Müşteri getirme kısmı pastanın üstündeki krema; asıl sattığın şey, dükkânın düzene girmesi. Çoğu satış \"müşteri gelir\" vaadiyle değil, \"dükkânım düzene girecek\" hissiyle kapanır — bunu aklından çıkarma.",
    "",
    "Senin kazancına gelince: getirdiğin işletme abone kaldığı sürece, **HER AY**, aboneliğin **KDV hariç net tutarı (2.000 TL) üzerinden anlaşılan yüzdeni** alırsın. Tek seferlik prim değil, birikimli gelir: bu ay 5 işletme bağlarsın, gelecek ay 5 daha — eskiler ödemeye devam ettikçe aylık gelirin üst üste biner. İşletme 2 yıl kalırsa 24 ay kazanırsın. Kazancını kendi panelinden anlık izlersin: hangi işletme aktif, bu ay ne tahakkuk etti, hepsi ekranda. Bunun bir sonucu şu: **doğru müşteriye, doğru anlatarak sat.** Yalan vaatle satılan abone ilk ay bırakır, senin gelirin de onunla birlikte gider. Memnun işletme = düzenli gelir.",
    "",
    "---",
    "",
    "## 2. MÜŞTERİ NASIL GELİYOR? (\"Bana iş gelir mi?\" sorusunun cevabı)",
    "",
    "Esnafın ilk sorusu hep budur: \"İyi güzel de, bu siteye müşteri geliyor mu?\" Cevabın şu:",
    "",
    "- Sitede her il ve ilçe için sayfa var; ama **arama motorlarına açık olanlar, halıcısı olan bölgelerin sayfaları.** Boş ilçe sayfaları bilerek `noindex` (Google'a bildirilen adres 1.054'ten 62'ye indirildi, 27 Temmuz) — çünkü binlerce boş sayfa bildirmek sitenin tamamına zarar veriyordu. Bir bölgeye ilk halıcı girdiğinde o bölgenin sayfası kendiliğinden aramaya açılıyor.",
    "",
    "> ⚠️ **\"973 ilçenin sayfası Google'da çıkıyor, aramalardan müşteri geliyor\" DEME (2026-07-29).** Sayfaların ~%98'i bilerek aramaya kapalı; bu cümle kendi kodumuzla çelişiyor. **\"Google'da birinci sıradasın\" da deme.** Doğrusu: *\"Bölgende sayfa açılır ve aramalara açık olur; oradan müşteri gelirse panelinde çıkar, komisyon almayız. Kaç müşteri geleceğine söz vermiyorum.\"* Sayı ve sıra vaadi yok.",
    "- Müşteri siteye girince **adresini veya konumunu** veriyor, sistem ona **en yakın işletmeleri** listeliyor. Sen o bölgede kayıtlıysan, listede sensin. Dükkânı yakın olanın avantajı otomatik.",
    "- Müşteri işletme profilinde ne görüyor? **Fotoğraflar, m² fiyat listesi, fiyat hesaplayıcı** (müşteri halısının ölçüsünü girip aşağı yukarı ne ödeyeceğini görüyor), **çalışma saatleri, müşteri yorumları ve yıldızlar, \"Doğrulanmış İşletme\" rozeti, WhatsApp butonu, sabit hat ve cep numarası.** Yani müşteri seni aramadan önce sana güveniyor.",
    "- Müşteri ister **tek tıkla online sipariş** veriyor, ister **WhatsApp'tan veya telefondan** ulaşıyor.",
    "- Üye olan müşteri **puan kazanıyor, yorum bırakıyor ve tek tıkla tekrar sipariş** veriyor — bir kere memnun ettiğin müşteri kolayca geri geliyor.",
    "- Henüz işletme olmayan şehirlerde müşteriler **\"işletme açılınca bana haber ver\"** listesine yazılabiliyor. O şehre **İLK kaydolan** işletme olursan, bekleyenlere sistem **otomatik e-posta** atıyor: \"Bölgende artık hizmet var.\"",
    "",
    "> ⚠️ **Bunu MEKANİZMA olarak anlat, SONUÇ olarak değil.** \"Hazır bekleyen bir müşteri listesine doğarsın\" DEME — bugün tüm Türkiye'de bekleyen kişi sayısı tek haneli. Doğru cümle: *\"Bölgende senden önce halıcı yokken haber isteyen olduysa, ilk giren sen olduğunda onlara e-posta gider.\"* Sayı söyleme; halıcı sonra o sayıyı sorar ve cevabı duyduğunda bütün anlattıkların değersizleşir.",
    "",
    "Ve en önemlisi: **siteyi telefondan aç, göster.** Anlatma, göster. Fiyat hesaplayıcıyı müşteri gözünden bir dene, işletmeciye de denet. Görmek inanmaktır.",
    "",
    "---",
    "",
    "## 3. İŞLETMEYE NE KAZANDIRIR? (Özellik değil, FAYDA anlat)",
    "",
    "Burası kitabın kalbi. Esnafa \"sipariş yönetim paneli\" deme; \"işlerin dağınıklığı biter\" de. Anlatırken en etkili yol, önce şu iki tabloyu çizmek:",
    "",
    "### Önce tablo: Mehmet Usta'nın günü — öncesi ve sonrası",
    "",
    "**ÖNCESİ (bugün çoğu dükkânda durum bu):** Mehmet Usta sabah dükkânı açıyor. Yıkama yaparken telefon çalıyor: \"Abla adresi bir mesaj at.\" Adres kâğıda yazılıyor, kâğıt kayboluyor. Şoför nerede belli değil, telefonla soruluyor. Bir müşteri arıyor: \"Benim halı ne oldu?\" — Usta hangi halı olduğunu hatırlamaya çalışıyor. Bir müşteri \"halımda leke çıkmış, sizde mi oldu\" diye tutturmuş; ispat yok, gönül koyma var. Bir sipariş telefonda kalmış, unutulmuş — müşteri başkasına gitmiş, haberi bile yok.",
    "",
    "**SONRASI (platformla aynı gün):** Mehmet Usta sabah paneli açıyor. Gece gelen siparişler listede. Tek tıkla onaylıyor; müşteriye bildirim e-postası gidiyor ve takip linkinden her adımı kendisi izliyor, Usta tek mesaj yazmıyor. Şoför mesaiye başlayınca konumu haritada. Halılar dükkâna gelince ölçüyor, net fiyatı panele giriyor, müşteri telefonundan onaylıyor. \"Halım ne oldu?\" diye arayan yok — müşteri zaten her adımı telefonundan izliyor. Kapıdan elden halı getiren amca mı geldi? O da panele giriliyor, ona da takip kodu çıkıyor. Bir sipariş 2 saat cevapsız kaldıysa sistem zil ve e-posta ile dürtüyor. Ay sonunda şoför raporları hazır. Mehmet Usta'nın telefonu artık sekreterlik için değil, iş yapmak için boşta.",
    "",
    "Bu tabloyu çizdikten sonra sor: **\"Usta, bu düzeni kurmak için ayrıca eleman mı tutacaksın, yoksa ayda 2.400 lira mı vereceksin?\"**",
    "",
    "Şimdi faydaları tek tek:",
    "",
    "### 3.1 Sipariş defteri cebinde — kâğıt, karalama, unutma devri biter",
    "Sipariş panele düşüyor: **onayla → halıyı al → yıka → hazır → teslimata çık → teslim et.** Her adım tek tık. Müşteri her adımı **kendi takip sayfasından** canlı izliyor — sen tek mesaj yazmıyorsun. Faydası ne? **Telefon trafiği azalıyor:** \"halım ne oldu abi?\" diye arayan müşteri, linke bakıp görüyor.",
    "",
    "> ⚠️ **\"Her adımda SMS gidiyor\" DEME (2026-07-29).** Sistemde SMS **hiç gönderilmiyor** (altyapı kapalı). Gerçekte giden bildirimler şunlar — Meta'daki şablon onaylarına göre canlıda doğrulandı:",
    ">",
    "> | Adım | WhatsApp | E-posta |",
    "> |---|---|---|",
    "> | Sipariş alındı | ✅ + \"Siparişimi takip et\" butonu | ✅ |",
    "> | Halı teslim alındı | 🕐 şablon onayda | ✅ |",
    "> | Kesin fiyat bildirildi, onay bekleniyor | ✅ + \"Fiyatı gör ve onayla\" butonu | ✅ |",
    "> | Yıkama başladı | 🕐 şablon onayda | ✅ |",
    "> | Şoför yola çıktı | ✅ + takip butonu | ✅ |",
    "> | Teslim edildi | ✅ + değerlendirme daveti | ✅ |",
    "> | İptal | ✅ | ✅ |",
    ">",
    "> **\"Halı alındı\" ve \"yıkama başladı\" adımları 02.08.2026'da eklendi.** Bugün bu",
    "> ikisinde **e-posta gidiyor**, WhatsApp'ları WhatsApp'ın (Meta) şablon onayında",
    "> — onaylanınca kendiliğinden devreye girecek. Satarken şunu de: *\"Sipariş,",
    "> fiyat onayı, yola çıkış ve teslimde WhatsApp gider; alım ve yıkama adımında",
    "> şimdilik e-posta gidiyor, müşteri hepsini takip sayfasından da görüyor.\"*",
    "> Onaylandığında bu satırlar ✅ olacak — **kitapta yazmayanı vaat etme.**",
    ">",
    "> **WHATSAPP CANLI (31.07.2026'da uçtan uca doğrulandı):** teslimatlar",
    "> `delivered` olarak izleniyor, beş bildirim şablonu da Meta onaylı ve",
    "> mesajların altında tıklanabilir buton var. Yani artık \"müşteriye WhatsApp'tan",
    "> bildirim gider, tek dokunuşla takip eder ve fiyatı onaylar\" DİYEBİLİRSİN —",
    "> bu cümle test edilmiş gerçektir. (SMS hâlâ YOK; SMS deme.)",
    ">",
    "> Aradaki diğer adımları müşteri takip sayfasından kendisi izler. **Dükkândan girdiğin manuel siparişte İLK mesaj (takip kodu) otomatik gitmez** — linki müşteriye SEN yollarsın. Sonraki adımlar (fiyat onayı, yolda, teslim) manuel siparişte de otomatik gider. Bunu doğru anlatmak senin de çıkarına: halıcı \"SMS gitmiyor\" dediğinde bütün anlattıkların değersizleşir.",
    "",
    "### 3.2 Fiyat kavgası biter: kesin fiyat bildirimi",
    "Herkes bilir bu derdi: telefonda \"şu kadar tutar\" dersin, halıyı alır ölçersin, fiyat değişir, müşteriyle tartışma çıkar, \"beni kandırdınız\" der, kötü yorum yazar. Bu sistemde şöyle: halıyı alıyorsun, ölçüyorsun, **net fiyatı panele giriyorsun, müşteri telefonundan görüp ONAYLIYOR.** Onaylanmış fiyat üzerinden iş dönüyor. Ne müşteri \"bana başka fiyat söylendi\" diyebiliyor, ne sen zarara giriyorsun. Yazılı, onaylı, kayıtlı — **fiyat tartışması diye bir şey kalmıyor.**",
    "",
    "**02.08.2026'dan beri bu adım ZORUNLU:** kesin fiyat girilmeden sipariş yıkamaya",
    "geçmiyor, sistem bırakmıyor. Yani \"unuttum, girmedim\" ihtimali kalktı; her işte",
    "müşteriye fiyat bildirimi gidiyor ve onay kaydı oluşuyor. Esnafa böyle anlat:",
    "*\"Sistem seni koruyor abi — fiyatı yazmadan halıyı makineye alamıyorsun. O kayıt",
    "sonra 'ben o parayı kabul etmedim' diyene karşı senin elinde duruyor.\"*",
    "",
    "### 3.3 \"Halım kayboldu, halım zarar gördü\" derdine kanıt: fotoğraflı kayıt",
    "Halı alınırken ve teslim edilirken **şoför uygulamasında/ekranında fotoğraf zorunlu** — o akışta sistem fotoğrafsız adımı geçirmez. Halıcı panelden fotoğrafsız ilerletirse bu da siparişin geçmişine ⚠️ notuyla yazılır (sessiz geçiş yok). Müşteri \"halımda leke vardı, siz yaptınız\" dediğinde elinde **tarihli, sipariş kayıtlı fotoğraf** var. \"Halım eksik geldi\" dediğinde teslim fotoğrafı var. Yıllardır esnafın başını ağrıtan ihtilafların ilacı bu. Bu özellik tek başına bir kavgayı, bir kaybı önlese parasını çıkarır — bunu aynen böyle söyle.",
    "",
    "### 3.3b \"Hangi halı kimin?\" — dükkânın en sinir bozucu sorusu (02.08.2026)",
    "Yoğun dükkânda halılar birbirine karışır. Etiket düşer, ıslanır, kâğıt kaybolur;",
    "teslimde yanlış halı gider, müşteri geri getirir, itibar gider. Sistemde çözümü",
    "şu: panelde **Halı Bul** ekranı var. Dükkânda ve yolda olan **bütün halıların",
    "fotoğraf duvarı** — her fotoğrafın üstünde **halı numarası**, altında **müşterinin",
    "adı, sipariş kodu ve telefonu.** Elindeki halıyı ekrandakiyle gözünle",
    "eşleştiriyorsun, kimin olduğu orada yazıyor. Üstte arama var: müşterinin adını,",
    "telefonunu ya da sipariş kodunu yazınca o müşterinin halıları çıkıyor.",
    "",
    "Numaralar kendiliğinden veriliyor: halıcı bir siparişe fotoğraf yükledikçe",
    "#1, #2, #3 diye sıralanıyor. Bir müşterinin 5 halısı varsa beşi de ayrı ayrı",
    "kayıtta; teslimde sayarken de işe yarıyor.",
    "",
    "**Esnafa şöyle anlat:** *\"Abi, elinde halı var kimin olduğunu bilmiyorsun.",
    "Telefonu aç, Halı Bul'a bas, fotoğrafından bul — altında adı yazıyor. Etiket",
    "yok, barkod yok, ıslanacak kâğıt yok.\"* Günde çok iş yapan dükkânda bu tek",
    "özellik bile abonelik parasını konuşturur.",
    "",
    "### 3.4 Şoförün nerede? Artık biliyorsun",
    "Şoförler için **mobil uygulama ve web ekranı** var. Şoför mesaiye başlayınca **konumu canlı olarak haritada** görünüyor. **Rota geçmişi** tutuluyor: bugün nereden nereye gitmiş, nerede durmuş — hepsi kayıtta. Ay sonunda **durak raporu** hazır. Esnafa şöyle anlat: \"Şoförün öğlen iki saat kayıp mı, benzin nereye gidiyor, araç gerçekten müşteride mi — hepsini ekrandan görürsün. Sormana gerek kalmaz, kayıt konuşur.\" Üstüne bir de müşteri tarafı var: **teslimata çıkan şoförü müşteri de haritada canlı izliyor.** Yemek kuryesini izler gibi halısının gelişini izliyor. \"Ne zaman gelecek?\" telefonları da biter, müşteri gözünde de \"bak bunlar kurumsal çalışıyor\" izlenimi kalır.",
    "",
    "### 3.5 Kapıdan gelen müşteri de sisteme girer",
    "\"Benim müşterim internetten gelmez, kapıdan gelir\" diyen esnafa cevap: kapıdan gelen müşteri için de **panelden manuel sipariş** açılıyor, ona da **takip kodu** veriliyor — ama dikkat: manuel siparişte otomatik bildirim GİTMEZ, takip linkini halıcı kendisi yollar. Ha internetten gelmiş ha kapıdan — **bütün işler tek ekranda.** Hangi halı kimin, hangisi yıkandı, hangisi teslim bekliyor; defter karıştırmak yok. Sokaktan gelen işle internetten gelen iş aynı defterde — tek panel, tek düzen.",
    "",
    "### 3.6 Kaçan iş kalmaz: geciken sipariş hatırlatması",
    "Sipariş geldi, fark edilmedi, müşteri bekledi bekledi başkasına gitti — en acı kayıp budur. Sistemde sipariş **2 saat yanıtsız kalırsa** işletmenin panelinde **zil** çalıyor; **24 saati geçerse** yönetime düşüyor ve müşteriye aynı şehirden alternatif öneriliyor. Uyusan bile sistem seni dürtüyor. Gelen iş kaçmıyor.",
    "",
    "### 3.7 Ufak ama gündelik hayatı rahatlatan şeyler",
    "- **Tatil modu:** kapalıyken profil uykuya alınır, boşuna sipariş düşmez, müşteri boşuna beklemez.",
    "- **Çoklu telefon:** sabit hat + ikinci GSM + WhatsApp — hepsi profilde, müşteri hangisinden isterse ulaşır.",
    "- **Google profili linki:** mevcut Google işletme sayfası da profile bağlanır.",
    "- **Takip kodu:** siteden gelen siparişte kod müşteriye WhatsApp ve (verdiyse) e-postayla gider; dükkândan girilen manuel siparişte linki halıcı kendisi iletir.",
    "- **Müşteri sadakati:** üye müşteri puan kazanır, tek tıkla tekrar sipariş verir.",
    "",
    "### 3.8 Özet cümle (ezberle)",
    "\"Abi bu sadece müşteri getiren bir site değil; **sipariş defterin, şoför takibin, müşteri mesajların, fiyat onayın, fotoğraf arşivin, hangi halı kimin** — dükkânın bütün düzeni tek panelde. Müşteri gelmesi işin bonusu.\"",
    "",
    "---",
    "",
    "## 4. FİYAT VE MODEL (\"Kaça mal olur, taahhüt var mı?\")",
    "",
    "Burada net ol, lafı dolandırma. Rakamlar şunlar ve asla değişmez:",
    "",
    "- **Aylık abonelik: 2.000 TL + KDV = 2.400 TL/ay.** Hepsi bu.",
    "- **Sipariş başına komisyon YOK. Müşteri başına pay YOK. Ciro kesintisi YOK.** İster ayda 5 iş alsın, ister 500 — ödediği aynı: 2.400 TL. Sınırsız sipariş, sınırsız kullanım.",
    "- **Yıllık taahhüt YOK.** İstediği ay bırakır. \"Memnun kalmazsan çıkarsın abi, kimse seni zorla tutmuyor\" — bunu söylemek güven verir, çünkü doğru.",
    "- **Kayıt anında yayın:** e-posta doğrulama → profil → sözleşme onayı → ödeme; ödeme geçtiği an profil **OTOMATİK yayına girer.** Onay kuyruğu yok, \"sizi arayacağız\" beklemesi yok. Bugün kaydolan bugün görünür.",
    "",
    "En güçlü karşılaştırman şu: **\"Başka sistemleri biliyorsun — her işten yüzde alırlar, sen büyüdükçe onlar kazanır. Burada tersi: sen büyüdükçe SEN kazanırsın, ödediğin para aynı kalır. Çok iş alan işletme için bu, işletme başına en ucuza gelen sistem demek. Müşterinin ödediği paranın tamamı senin cebine.\"**",
    "",
    "### Fiyatı asla çıplak söyleme — hesabıyla beraber söyle",
    "2.400 tek başına söylenirse büyük gelir. Her zaman hesapla birlikte ver:",
    "",
    "- **Günlük hesap:** 2.400 TL / 30 gün = **günde 80 lira.** \"Usta, günde 80 liraya sana sekreter, çağrı merkezi, şoför takip sistemi ve internet vitrini geliyor.\"",
    "- **Amorti hesabı:** Esnaf kendi m² fiyatını bilir — hesabı ONA yaptır: \"Ayda kaç halı fazladan yıkasan bu 2.400'ü çıkarırsın?\" Kendi ağzıyla \"çıkarır\" desin. Sen sipariş sayısı ya da kazanç rakamı UYDURMA; hesabı o yapsın, sonuç onun sonucu olsun.",
    "- **Görünmeyen kazançlar:** kaçan siparişin hatırlatması, biten fiyat kavgası, fotoğraflı kanıt, şoför takibi — bunlar da para. Bir tane \"halım kayboldu\" kavgası önlense o para zaten çıkar.",
    "",
    "---",
    "",
    "## 5. SIK İTİRAZLAR VE CEVAPLAR (İşin kalbi — kısa halini ezberle, gerekince uzat)",
    "",
    "### 1) \"Zaten müşterim var, bana site lazım değil.\"",
    "**Kısa:** \"Abi zaten müşterisi olan kazanır bu sistemden. Sen mevcut işini düzene sokuyorsun; internetten gelen üstüne bonus.\"",
    "**Uzun:** \"Şunu sorayım: mahalleye yeni biri taşınınca kimden yıkatıyor? İnternete bakıyor. Orada seni değil rakibini görürse, eski müşterin bile bir gün oraya kayar. Bu sistemde olmak sadece yeni müşteri değil, mevcut müşteriyi koruma meselesi. Hem panel, fotoğraflı teslim, fiyat onayı, şoför takibi — bunlar müşterin ÇOK olduğu için lazım sana, az olduğu için değil. Kapıdan gelen müşterini de panele giriyorsun; takip kodu onun için de çıkıyor — linki sen yolluyorsun.\"",
    "",
    "### 2) \"Ben internetten anlamam, yaşlıyım, uğraşamam.\"",
    "**Kısa:** \"Anlamana gerek yok abi. Telefon kullanmayı biliyorsan bu sistemi kullanırsın. Panel üç düğme: onayla, hazır, teslim. Bildirimleri sistem kendi atıyor.\"",
    "**Uzun:** \"Kaydını beraber yaparız, yanında oturur profili beraber doldururuz, fotoğrafları beraber yükleriz. İlk siparişin gelene kadar telefonun ucundayım. WhatsApp kullanıyor musun? Kullanıyorsun. Bu ondan zor değil. Sen halını yıka, gerisi otomatik.\"",
    "",
    "### 3) \"2.400 lira pahalı.\"",
    "**Kısa:** \"Günde 80 lira abi. Kendi m² fiyatınla hesapla: ayda kaç halı fazladan yıkasan çıkar bu para?\"",
    "**Uzun:** \"Bir de sadece gelen müşteriyi sayma: bir tane 'halım kayboldu' kavgası önlense, bir tane fiyat tartışması bitse, bir tane unutulan sipariş kurtulsa — o para zaten çıkar. Ve taahhüt yok: bir ay dene, ay sonunda otur hesabını kendin yap, tutmadıysa bırak.\"",
    "",
    "### 4) \"Komisyon mu kesiyorsunuz? Bu siteler hep iş başına para alır.\"",
    "**Kısa:** \"Hayır abi, işte bütün fark bu. Sipariş başına tek kuruş kesinti yok. Sabit 2.400, ister 5 iş al ister 500.\"",
    "**Uzun:** \"Diğer sistemleri biliyorsun — her işten yüzde alırlar, sen büyüdükçe onlar kazanır. Burada tersi: sen büyüdükçe SEN kazanırsın, ödediğin aynı kalır. Müşterinin ödediği paranın tamamı senin cebine.\"",
    "",
    "### 5) \"Düşüneyim / sonra bakarız / kartını bırak.\"",
    "**Kısa:** \"Tabii düşün abi. Yalnız sen düşünürken bu sayfalar yayında; ilçene ilk giren kim olursa yorum, puan, müşteri önce onda birikiyor.\"",
    "**Uzun:** \"Taahhüt yok — yani 'düşüneyim' dediğin şeyin riski zaten yok. Bir ay dene, beğenmezsen bırak; kaybın bir aylık ücret. Ama altı ay sonra girersen, rakibin altı aylık yorum ve müşteri biriktirmiş olacak. İstersen beş dakikada kaydını beraber yapalım, ay sonunda hesabı sen kendin çıkar.\" *(Bölge gerçekten boşsa ekle: \"Hele senin şehirde hiç işletme yok — bekleyen müşteri listesine ilk kaydolana sistem otomatik haber veriyor. İlk sen ol.\")*",
    "",
    "### 6) \"Sitede rakiplerim de olacak, ne anladım ben bu işten?\"",
    "**Kısa:** \"Rakibin zaten internette abi. Soru şu: müşteri aradığında sen de görünecek misin, yoksa sahayı ona mı bırakacaksın?\"",
    "**Uzun:** \"Müşteri en yakını görüyor — senin mahallenden arayan önce seni bulur. Üstüne fotoğrafların düzgünse, yorumların iyiyse, fiyatın yerindeyse müşteri seni seçer. Görünmeyen kaybeder, bu kadar basit.\"",
    "",
    "### 7) \"Elemanım yok, şoförüm yok, ben küçüğüm.\"",
    "**Kısa:** \"Sistem tek kişilik dükkâna da uyar abi. Şoför modülünü kullanmazsın; sipariş paneli ve gelen müşteri sana yeter.\"",
    "**Uzun:** \"Hatta küçük işletmeye daha çok lazım — tabelan küçük, reklamın yok; bu site senin vitrinin olur. Büyürsen şoför takibi, raporlar hazır bekliyor.\"",
    "",
    "### 8) \"Beni sisteme bağlayıp sonra fiyat mı artıracaksınız? Güvenli mi?\"",
    "**Kısa:** \"Aylık ödersin, taahhüt yok, istediğin ay bırakırsın. Seni bağlayan hiçbir şey yok — sistemi tutan tek şey memnuniyetin.\"",
    "",
    "### 9) \"Müşteri yorumu kötü gelirse?\"",
    "**Kısa:** \"Fotoğraf kaydın var, fiyat onayın var, her adım kayıtlı. Bu sistemde ağzı laf yapan değil, işi düzgün yapan öne çıkar. İyi iş yapan esnafın eli güçlenir.\"",
    "",
    "### \"Kaç sipariş gelir?\" sorusuna standart cevap (garantiye ÇEKME):",
    "\"Onu ilçene, fiyatına, yorumlarına göre zaman gösterir abi. Ben sana kapıyı açıyorum; kapıdan kaç kişi girer garanti edemem. Ama kapın kapalıysa hiç kimse girmez, o kesin.\"",
    "",
    "---",
    "",
    "## 6. SATIŞI KAPATMA VE KOD AKIŞI (Ekmeğin burada — iyi oku)",
    "",
    "### Önce konuşmayı kapanışa götür",
    "Konuşmanın sonunda mutlaka NET bir adım iste; \"haber verirsin\" deyip çıkma. Durumuna uyanı kullan:",
    "",
    "1. **Direkt kapanış:** \"Hadi abi, beş dakikada kaydını beraber yapalım. Ödemen geçtiği an profilin yayında, ilk siparişini bekleyelim.\"",
    "2. **Deneme kapanışı:** \"Bir ay dene. Ay sonunda otur hesabını yap: gelen sipariş, biten telefon trafiği, önlenen kavga. Değmediyse bırakırsın, kimse arkandan koşmaz.\"",
    "3. **Öncelik kapanışı:** \"Senin ilçede öne geçen, yorumu ve puanı önce biriktiren kazanır. İlk sen ol, sonra girenler seni kovalasın.\"",
    "4. **Hesap kapanışı:** \"Günde 80 lira. Bu hesabı bozan bir şey görüyorsan söyle; göremiyorsan başlayalım.\"",
    "5. **Yumuşak kapanış (kesin hayır alırsan):** \"Tamam abi, zorlamak yok. Sitenin adını yazıyorum: enyakinhaliyikamaservisi.com. Kendi ilçene bak, kimler var gör. Bir hafta sonra bir çayına yine uğrarım.\" — Ve GERÇEKTEN uğra. Çoğu satış ikinci ziyarette kapanır.",
    "",
    "### Kayıt akışı — esnafla BERABER yap",
    "1. Siteden işletme kaydı açılır, **e-posta doğrulanır.**",
    "2. **Profil doldurulur:** fotoğraflar, m² fiyat listesi, çalışma saatleri, telefonlar, adres. Bunları güzel doldurtun — vitrin burası; kötü fotoğraflı profil müşteri kaçırır.",
    "3. **Sözleşme ekranda dijital onaylanır.**",
    "4. **Ödeme yapılır** — ve işletme **OTOMATİK yayına girer.** Beklemece yok.",
    "",
    "### Senin kodun — İYİ DİNLE, para kazandıran kısım bu",
    "- Kayıt formunda **\"referans kodu\"** alanı var. Senin kodun **oraya, kayıt sırasında** girilecek.",
    "- Kodlar **TEK KULLANIMLIK.** Her müşteri adayı için **panelinden YENİ kod üretirsin.** Bir kodu iki işletmeye veremezsin. Dükkâna gitmeden, telefona sarılmadan önce panelden taze kod al.",
    "- **Kod girilmeden kayıt tamamlanırsa o işletme senin hanene yazılmaz ve emeğin boşa gider.** En sağlamı: kaydı işletmeyle birlikte, yüz yüze veya telefonda adım adım yapmak ve kodun girildiğini gözünle görmek. Yanında olamıyorsan kodu eline yazıp ver: \"Bunu şu kutuya yazacaksın\" de, sonra teyit et.",
    "",
    "### İndirim yetkin varsa (yoksa bu bölümü tamamen atla)",
    "Bazı komisyoncuların **indirim tanımlama yetkisi** vardır: ürettiğin koda **belirli bir yüzde ve süre** gömülür; işletme o süre boyunca aboneliği indirimli öder. Bunu kapanış kozu olarak sakla: \"Bak, bugün benim kodumla kayıt olursan ilk [X ay] aboneliği [%Y] indirimli ödersin. Bu fırsat bu koda özel.\" Yetkin YOKSA indirim lafını hiç açma — tutamayacağın söz hem senin hem platformun itibarını yakar.",
    "",
    "### Satıştan sonrası",
    "Sat ve kaybol değil. Ara sıra uğra, \"panel nasıl gidiyor abi\" de, takıldığı yerde yardım et. Senin gelirin abonelik sürdükçe akar; o işletme sistemde kaldıkça kazanan sensin.",
    "",
    "---",
    "",
    "## 6b. DEMO — ANLATMA, GÖSTER (2026-08-02: iki ekran, tek tık)",
    "",
    "Panelinde *Demo Panelim* kutusunda **iki düğme** var, ikisi de şifre sormaz:",
    "",
    "- **🏪 Demo halıcı paneli** — sipariş listesi, kasa, fotoğraflı teslim, fiyat onayı",
    "- **🚚 Demo şoför ekranı** — işin şoföre nasıl düştüğü, fotoğraf, teslim kapatma",
    "",
    "**Sıra önemli:** önce halıcının kendi göreceği paneli aç, dolu sipariş listesini",
    "göster. Sonra şoför ekranına geç: *\"Sen buradan bakıyorsun, şoförün de şunu",
    "görüyor — nerede olduğunu, hangi halıyı aldığını.\"* İki ekranı arka arkaya",
    "görmek, on dakikalık anlatımdan daha ikna edici.",
    "",
    "Dönüş için ekranın üstündeki mor şeritteki **\"Komisyoncu paneline dön\"**",
    "düğmesine bas. Demo verileri sahtedir; kimseye mesaj gitmez, hiçbir sayaçta",
    "görünmez.",
    "",
    "**Ücretsiz deneme yetkin varsa** (kod üretme kutusunda \"Ücretsiz deneme\" listesi",
    "çıkıyorsa): kararsız halıcıya *\"Bir ay bedava dene, beğenmezsen bırakırsın\"*",
    "diyebilirsin. Deneme süresince komisyon işlemez — kazancın halıcı ilk ödemeyi",
    "yaptığında başlar. Yetkin yoksa bu sözü VERME.",
    "",
    "---",
    "",
    "## 7. CEP ÖZETİ (Asansör konuşması — ezberle, 30 saniyede anlat)",
    "",
    "> **SIRA DEĞİŞTİ (2026-07-29) — önce PANEL, en sonda site.** Eski açılış \"her ilçesi için sayfası olan, müşterinin seni bulduğu sistem\" diyerek işe müşteri vaadiyle başlıyordu. Halıcı 2. ayda \"bana müşteri gelmedi\" dediğinde cevabın olmuyordu. Yeni sırayla cevabın hazır: *\"Zaten onun parasını almadık; ödediğin şey panel — o çalışıyor mu?\"*",
    "",
    "\"Abi, halı yıkamacılara özel bir işletme yazılımı var: enyakinhaliyikamaservisi.com. Şoförünü mesai boyunca haritadan izliyorsun — nerede, kaç dakika durmuş belli; geçmiş günün rotasını baştan oynatabiliyorsun. Halıyı ölçünce net fiyatı panelden bildiriyorsun, müşteri kendi telefonundan onaylıyor ve onaydan sonra fiyat değişmiyor — fiyat kavgası kapıda değil ekranda bitiyor. Dükkânda halılar karıştıysa telefondan fotoğraf duvarına bakıyorsun, her halının numarası ve sahibinin adı orada yazıyor. Şoför teslimde fotoğraf çekmeden 'teslim ettim' diyemiyor, o kayıt tartışmada senin elinde duruyor. Ay sonunda kâr mı ettin zarar mı, tek ekranda görüyorsun: maaş, kira, deterjan gibi giderleri bir kez tanımlıyorsun her ay kendiliğinden düşüyor, teslim ettiğin siparişin geliri deftere otomatik giriyor. Kapıdan gelen müşterini de panele yazıp takip kodunu WhatsApp'tan yolluyorsun — yani siteden hiç sipariş gelmese bile yazılım her gün işine yarıyor. Bunun maliyeti ayda 2.000 lira artı KDV, yani 2.400 lira; günde 80 lira. Sipariş başına komisyon yok, taahhüt yok, istediğin ay bırakırsın. Bir de şu var, üstelik ayrıca parasını almıyoruz: bölgenin sayfasında fotoğraflarınla ve fiyat listenle listeleniyorsun, oradan müşteri gelirse panelinde çıkıyor. Kaç müşteri geleceğine söz vermiyorum — sistem yeni, oradan gelen sipariş sayısı bugün az. Söz vermek yerine o tarafın parasını almamayı seçtik.\"",
    "",
    "---",
    "",
    "## SON KONTROL: ALTIN KURALLAR",
    "",
    "1. **Göster, anlatma.** Siteyi telefondan aç, fiyat hesaplayıcıyı dene.",
    "2. **Uydurma.** Bu kitapta yazmayan hiçbir özelliği söyleme. \"Google'da birinci çıkarsın\" DEME, sipariş sayısı garantisi VERME. Yukarıdaki her şey gerçektir ve sistemde çalışır durumdadır — gerçeği anlatmak hem kolaydır hem kalıcıdır.",
    "3. **Dinle.** İki soru sor (\"İnternetten müşteri geliyor mu? Sipariş defterini nasıl tutuyorsun?\"), derdini öğren, oradan gir. Müşteri azlığından dert yanana Bölüm 2'yi, karışıklıktan ve kavgadan dert yanana Bölüm 3'ü öne al. Ezber makinesi gibi konuşan satıcıyı esnaf kapıdan sepetler.",
    "4. **Fiyatı hesapsız söyleme.** Her zaman \"günde 80 lira\" ve esnafın kendi m² hesabıyla beraber.",
    "5. **Kaydı beraber yap, kodunun girildiğini gözünle gör.** Her aday için panelden yeni kod üret — kodlar tek kullanımlık.",
    "6. **Uzun vadeli düşün.** Kazancın abonelik sürdükçe akar. Doğru esnafa doğru anlatarak sat; memnun işletme senin düzenli maaşındır.",
  ].join("\n"),
  "saha-karti": [
    "# SAHA KARTI — Tek Sayfa",
    "## Dükkân kapısında telefondan bakılacak özet. Vaat yok, işlev var.",
    "",
    "*Kaynak: Pazarlamacı El Kitabı. Bu kart özetidir; ayrıntı ve uzun cevaplar orada.*",
    "",
    "---",
    "",
    "## NE SATIYORSUN? (tek cümle)",
    "",
    "**Halı yıkamacının bütün gününü tek panelde toplayan işletme yazılımı** —",
    "sipariş defteri, şoför takibi, fotoğraflı teslim kaydı, fiyat onayı, kasa.",
    "Bölge sayfasında listelenme üstüne gelir; onun için ayrıca para alınmaz.",
    "",
    "---",
    "",
    "## HANGİ DERDİ ÇÖZÜYOR? (halıcının diliyle)",
    "",
    "| Halıcının derdi | Sistemde çözümü |",
    "|---|---|",
    "| \"Siparişi kâğıda yazdım, kayboldu\" | Sipariş paneli — her iş listede, hiçbiri unutulmaz; 2 saat bekleyeni sistem dürter |",
    "| \"Telefon susmuyor: *halım ne oldu?*\" | Müşteriye takip linki + **butonlu WhatsApp** (sipariş alındı · fiyat onayı · yolda · teslim · istersen \"hazır\") **+ e-posta** (bunlara ek olarak halı alındı ve yıkama başladı adımlarında da) — müşteri kendisi bakar, seni aramaz |",
    "| \"Fiyatta anlaşamadık, *ben ona evet demedim* kavgası\" | Kesin fiyatı panelden bildirirsin, müşteri **kendi telefonundan onaylar** — onay saatiyle kayıtta, tartışma bitti. **Fiyat girilmeden sipariş yıkamaya geçmiyor**, sistem unutturmuyor |",
    "| \"*Halımda leke vardı, sizde oldu* suçlaması\" | Alım ve teslimde **fotoğraf** (şoför akışında zorunlu), yıkamada istersen — zaman damgalı, kanıt sende |",
    "| \"*Halılar karıştı, hangisi kimin bilmiyorum*\" | **Halı Bul**: dükkândaki tüm halıların fotoğraf duvarı — her karede halı numarası, altında müşteri adı + sipariş kodu; ad/telefon/kodla ara. Etiket, barkod, ıslanacak kâğıt yok |",
    "| \"Şoför nerede, üç saattir yok\" | Canlı harita + dün nereye gitti, kaç dakika durdu (rota geçmişi + durak raporu) |",
    "| \"Şoförün üstünde ne kadar nakit kaldı?\" | Gün sonu **mutabakat ekranı**: kim ne topladı, ne teslim etti, üzerinde ne var |",
    "| \"Ay bitti — kâr mı ettim zarar mı, bilmiyorum\" | **KASA**: teslim gelirleri otomatik işler; kira/maaş/deterjanı bir kez tanımlarsın, her ay kendi düşer, kâr-zarar hazır |",
    "| \"Kapıdan gelen müşteri defterde kalıyor\" | Onu da panele yazarsın — takip kodu çıkar (**ilk linki sen iletirsin**, sonraki adımların bildirimi otomatik gider) |",
    "",
    "**Ezber cümle:** \"Abi bu sadece müşteri getiren site değil; sipariş defterin,",
    "şoför takibin, fiyat onayın, fotoğraf arşivin, hangi halı kimin — dükkânın",
    "bütün düzeni tek panelde. Müşteri gelmesi işin bonusu.\"",
    "",
    "---",
    "",
    "## FİYAT (çıplak söyleme, hesabıyla söyle)",
    "",
    "**2.000 TL + KDV = 2.400 TL/ay → günde ~80 lira.**",
    "\"Kendi m² fiyatınla hesapla: ayda kaç halı fazladan yıkasan çıkar bu para?\"",
    "- Sipariş başına komisyon **YOK** · ciro payı **YOK** · taahhüt **YOK** — istediği ay bırakır.",
    "",
    "---",
    "",
    "## EN SIK 3 İTİRAZ — KISA CEVAP",
    "",
    "1. **\"Zaten müşterim var, lazım değil.\"** → \"Zaten müşterisi olan kazanır",
    "   bundan: panel, fotoğraflı teslim, şoför takibi müşterin **çok** olduğu için",
    "   lazım. İnternetten gelen üstüne bonus.\"",
    "2. **\"2.400 pahalı.\"** → \"Günde 80 lira. Bir *halım kayboldu* kavgası önlense,",
    "   bir unutulan sipariş kurtulsa, çıkar. Bir ay dene, hesabını kendin yap.\"",
    "3. **\"Komisyon kesiyor musunuz?\"** → \"Tek kuruş yok. Sabit aidat; 5 iş de",
    "   alsan 500 de, aynı. Müşterinin ödediği paranın tamamı senin cebine.\"",
    "",
    "---",
    "",
    "## KOD AKIŞI (paranın kazanıldığı yer)",
    "",
    "1. Panelden **\"+ Kod Üret\"** → `HYK-XXXXXX` (tek kullanımlık, sadece bu müşteriye).",
    "2. Kaydı halıcıyla **BERABER** yap; kodu formdaki \"Referans kodu\" alanına",
    "   girdiğini **gözünle gör** — kod girilmezse işletme senin hanene yazılmaz.",
    "3. Ödeme gerçekleştiğinde komisyonun otomatik işler; her ayın son günü havale.",
    "",
    "---",
    "",
    "## 🔴 YASAK CÜMLELER (söylersen ikinci ayda yüzüne vurulur)",
    "",
    "- ❌ \"Ayda şu kadar sipariş gelir\" / kazanç rakamı → ✅ *\"Kaç müşteri geleceğine söz vermiyorum; o tarafın parasını da almıyoruz.\"*",
    "- ❌ \"Google'da birinci çıkarsın\" → ✅ *\"Bölgende sayfan açılır, aramalara açık olur.\"*",
    "- ❌ \"SMS gider\" → SMS YOK. ✅ *\"WhatsApp + e-posta gider, mesajda takip butonu var.\"*",
    "- ❌ \"Her adımda WhatsApp gider\" → **alım ve yıkama** adımında bugün yalnız e-posta gider (WhatsApp şablonu onayda). ✅ *\"Sipariş, fiyat onayı, yola çıkış ve teslimde WhatsApp; hepsi takip sayfasında.\"*",
    "- ❌ İndirim sözü (yetkin yoksa) → panelinde indirim alanı yoksa yetkin yok demektir.",
    "- ❌ Deneme sözü (yetkin yoksa) → kod üretme kutusunda \"Ücretsiz deneme\" listesi yoksa yetkin yok.",
    "",
    "**Altın kural: anlatma, GÖSTER.** Kendi demo panelini aç, telefonu çevir —",
    "görmek inanmaktır.",
  ].join("\n"),
};
